### ISSUE TITLE
IPFS Password Manager

### ISSUE THREAD

**Issue by harryisgood** [filecoin-project/devgrants#1027]
### 1. What is your project? (max 100 words)

I was tired of trying to keep track of all my passwords and didn't want them to all be stored with Google so I said it would be better to store them on my own so I have control of where they are stored. I use IPFS to store the passwords and I want to expand this project by creating a user login portal and allowing users to create accounts.

### 2. Project links
  
Link to Github repo: https://github.com/harryisgood/ipfs-pw-manager
Link to demo or website, if applicable: https://www.youtube.com/watch?v=GG6gnpjQN04
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

IPFS is used as the storage for this password manager.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- add a login portal for users
- build a way for users to create accounts
- improve the password generation algorithm
- Improve the UI
- Figure out an algorithm for encrypting the password files on IPFS
- Improve encryption for password files

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  
Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. It's just me
* How did you learn about our microgrant program? Google
* If your project was created as part of an event or hackathon: N/A
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) N/A
  * Please link to your hackathon submission N/A

**Comment by ErinOCon** [comment]
Hi @harryisgood, thank you for your proposal! Can you describe how you will approach achieving the outlined steps in item 4?

**Comment by rickityjo** [comment]
I plan to use built-in flask libraries for the UI and login pages. I studied some cryptography in college so I would like to see if I can use this knowledge to build my own algorithm otherwise I will use one available in python like this one [for example](https://pypi.org/project/cryptography/).

Currently, I store the password files as plain text files but I want to upgrade this to store the passwords in an encrypted text file that way if someone gets access to the file they cannot read the passwords. To do this I would again like to build the encryption algorithm but if not possible I would use one already available.

The other thing I would like to do is add a feature to recommend a user a new password for their accounts.

I would do this by generating a sentence and replacing random characters with non-alphanumeric characters and have another algorithm which would generate a sentence of random words from a very [large text file](http://www.mieliestronk.com/wordlist.html) but replace words with the first 2 letters of the word and combine these diads together to form a single password, interspersed with non-alphanumeric characters.

**Comment by harryisgood** [comment]
I plan to use built-in flask libraries for the UI and login pages. I studied some cryptography in college so I would like to see if I can use this knowledge to build my own algorithm otherwise I will use one available in python like this one [for example](https://pypi.org/project/cryptography/).

Currently, I store the password files as plain text files but I want to upgrade this to store the passwords in an encrypted text file that way if someone gets access to the file they cannot read the passwords. To do this I would again like to build the encryption algorithm but if not possible I would use one already available.

The other thing I would like to do is add a feature to recommend a user a new password for their accounts.

I would do this by generating a sentence and replacing random characters with non-alphanumeric characters and have another algorithm which would generate a sentence of random words from a very [large text file](http://www.mieliestronk.com/wordlist.html) but replace words with the first 2 letters of the word and combine these diads together to form a single password, interspersed with non-alphanumeric characters.

**Comment by ErinOCon** [comment]
Hi @harryisgood, can you provide a preferred email address to confirm payment details?

**Comment by harryisgood** [comment]
harryjones97@proton.me - this is a good email address for me

**Comment by ErinOCon** [comment]
thank you!

**Comment by ErinOCon** [comment]
Hi @harryisgood, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
