### ISSUE TITLE
Next Step Microgrant: db3 network

### ISSUE THREAD

**Issue by imotai** [filecoin-project/devgrants#1230]
### 1. What is your project, and what problem does it solve? (max 100 words)
DB3 is a community-driven decentralized layer2 database network.

### 2. Project links
  
Link to Github repo:https://github.com/dbpunk-labs/db3
Link to demo or website, if applicable:db3.network
License:apache 2.0

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
<img width="913" alt="image" src="https://user-images.githubusercontent.com/8623385/206937170-53af390e-b7fd-4034-acdf-0cb77ec9d690.png">

DB3 will use filecoin to archive historical blocks and cold data state to reduce node storage costs
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
  Yes
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will design and implement the archive feature on fvm testnet
step1: design the db3 archive protocol  based on the fvm
step2: develop and test the archive smart contract on fvm 
step3: add archive feature to db3 storage node 
         
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * imotai (database& rust & blockchain & smart contract)
        * email: codego.me@gmail.com
        * github: github.com/imotai     
* How did you learn about our microgrant program?
    * from Isabella(webchat)

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 
  * Please link to your hackathon submission

**Comment by eshon** [comment]
@imotai Can you provide more specific detail on how FVM is involved? What will your FEVM contracts do?

**Comment by imotai** [comment]
@eshon we will use the smart contact to manage the state of archive，for example repay the miners of filecoin to implement the permanent archive

**Comment by ErinOCon** [comment]
Hi @imotai, thank you for your proposal. This microgrant has been approved! We will send an email to confirm next steps.

**Comment by ErinOCon** [comment]
Hi @imotai, can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see https://github.com/filecoin-project/community/discussions/585#resources, or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

Please be in touch with any questions!

**Comment by ErinOCon** [comment]
HI @imotai, can you provide an update on grant progress in this thread?

**Comment by ErinOCon** [comment]
Hi @imotai, we have not heard from your team and will be resolving this project. 

Please contact grants@fil.org with any questions.
