### ISSUE TITLE
Filecoin Bond Solution

### ISSUE THREAD

**Issue by songsjun** [filecoin-project/devgrants#1291]
### 1. What is your project, and what problem does it solve? (max 100 words)
Based on FVM, miners mortgage the owner account to the smart contract, and issue bonds based on their reputation and pledged assets. Investors share the mining revenue by purchasing bonds. Miners use the funds raised to expand their operations.

### 2. Project links
  
Link to Github repo: https://github.com/fildaio/FilBonDA
Link to demo or website, if applicable: Not ready
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
This project requires a deep combination of Filecoin nodes and FVM. We need to be able to realize all the functions of the owner account through smart contracts, and also complete bond issuance and fund management based on smart contracts. This is an experiment to financialize Filecoin nodes.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
YES

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We are working on a product prototype and will have a website and an example in 1, 2 months. After these are verified, the development and audit of the contract will be completed, and we hope to release our products simultaneously when FVM goes online.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Sure, Np.

### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
no
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Github handle: [songsjun](https://github.com/songsjun)
Repo: https://github.com/fildaio/FilBonDA

* How did you learn about our microgrant program?
From my friend who is a miner.

**Comment by ErinOCon** [comment]
HI @songsjun, thank you for your patience with our review. This microgrant has been approved! Can you provide an email address to discuss next steps?

**Comment by ErinOCon** [comment]
Hi @songsjun, can you confirm if you are still interested in proceeding with this project?

**Comment by ErinOCon** [comment]
HI @songsjun, please let me know if you will be providing contact information.

**Comment by songsjun** [comment]
> HI @songsjun, thank you for your patience with our review. This microgrant has been approved! Can you provide an email address to discuss next steps? 

Sjun.song@gmail.com
Sorry I lost this url, so late to find again

**Comment by ErinOCon** [comment]
Hi @songsjun, this microgrant has been approved! We will send an email to confirm payment details. In regards to the final report for this project, here are some things we are looking for:

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin.

**Comment by songsjun** [comment]
Thanks Erin, we will update the info later, thanks for your support

**Comment by ErinOCon** [comment]
Hi @songsjun, can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see https://github.com/filecoin-project/community/discussions/585#resources, or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

Please be in touch with any questions!

**Comment by ErinOCon** [comment]
Hi @songsjun, can you provide an update on your grant progress?

**Comment by ErinOCon** [comment]
Hi @songsjun, we have not heard from your team and will be resolving this project.
