### ISSUE TITLE
RFP: Storage helper libraries

### ISSUE THREAD

**Issue by pooja** [filecoin-project/devgrants#13]
This RFP is all about creating libraries that perform useful storage workflow functionality! Read more about it at [this link](https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-storage-helper-libraries.md), and add any questions/comments you may have in this issue!

**Comment by yangjian102621** [comment]
@pooja 
Hi, i had moved the project [java-filecoin-api-client](https://github.com/filecoin-shipyard/java-filecoin-api-client) to `filecoin-shipyard` orgnization. Can I still participate in Filecoin Devgrants use this project, as a `devtools-library`?

**Comment by pooja** [comment]
Hey! Yes absolutely! Please submit a PR with your proposal for the project, and we will review it with other proposals in September!

**Comment by waynewyang** [comment]
I want to clarify about the file ingestion + splitting.
- "go-filecoin client import" is alreay support the functions for big file, it splits the files to DAG. 
    Can the file/directory split functions be implemented in go-filecoin.   
-  If the split function will be implemented by storage helper libraries.
    - The workflow is that user will split the file firstly by helper libraries, then import the chunk to filecoin throught "go-filecoin client import"?
    - the big file will be split by helper libraries into DAG format or other customize format?

**Comment by mishmosh** [comment]
@waynewyang Sorry for the delay. Yes, the workflow is (1) split into chunks smaller than 1 sector and then (2) import the chunk to filecoin. To keep `go-filecoin` lean as possible, our preference at this point is for (1) to be handled outside of `go-filecoin`. The helper libraries do not have to split into the complete DAG -- just smaller than 1 sector, in a standard unix format, because `go-filecoin` cannot make deals larger than a sector. 

For example, let's say you have 10 folders that contains 100 video files each. The video files are 21GB each (size of a 60-minute video from a 4k smartphone). Total is 20TB of data, but this is bigger than any `go-filecoin` sector. The helper would split this into chunks smaller than 1 sector, so that when imported to `go-filecoin` it can successfully make a deal.

**Comment by waynewyang** [comment]
@mishmosh thanks.
