### ISSUE TITLE
Next Step Microgrant: SPex(Storage Providers Exchange)

### ISSUE THREAD

**Issue by mingming-tang** [filecoin-project/devgrants#1301]
### 1. What is your project, and what problem does it solve? (max 100 words)
SPex is a decentralized storage provider exchange space on FVM.
The first phase of development enables：
* SPs realize the future unlocking rewards immediately (no need to wait 180 days)
* Anti-censorship of SPs ownership transfer via the anonymity of transaction
* SPs realize the monetary value of special IDs or the IDs with historical reputation
* Better utilization of SP resources lightens the network burden caused by the over-use of ID numbers, effectively recycling the already existing ones; also provides the marketplace when later the network could charge a fee for node creation to increase revenue (an FIP required).

### 2. Project links
Link to Github repo: https://github.com/SPex-team/SPex

Link to demo or website, if applicable: https://www.spex.website/

License: MIT, APACHE2

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

SPex serves Filecoin Storage Providers and to be running on Filecoin network. The key part of SPex implementation is a smart contract building on Filecoin Virtual Machine. 

b) Is this project contributing to the upcoming FVM launch? (Yes or No)
  Yes
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Phase 2:
SPs would be able to transfer beneficiaries with terms(time frame & Quota) to allow the financial opportunity to happen： allow ABS as a financing tool, derivative（Shorting）. 

Phase 3:
We would develop the bidding mechanism (not only the order book). The ID would become more like an NFT.
In the long run, accompanied by the development of the Filecoin ecosystem, SPex aims to provide liquidity to the network not only for SPs accounts but also the deal orders.

This grant is mainly for the development of a smart contract and user interface, trial on HyperSpace testnet, and later implementation on Filecoin mainnet when FVM M2.2 is launched.
1. Develop an SP exchange order book Actor, where SPs give quotations on nodes. If the buyer accepts the deal, the transaction will be executed by the smart contract automatically.
2. A website for better UX for SPs to operate on
3. Cooperate with Filecoin client implementators (Lotus/Venus) to provide ordering tools
4. Develop a bidding Actor, a more efficient valuation mechanism for SPs. The buyers can bid for the nodes they are willing to buy.
5. To be extended and migrated to a Filecoin native NFT exchange (for later consideration)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.  

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

  Not yet so far, but we will be willing to join a hackathon in next months.
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Mingming Tang, monden.tang@gmail.com, https://github.com/mingming-tang, Founder && Full Stack Developer
  * Zixian Liu, jinming0603.lucky@gmail.com, https://github.com/ljinming, Co-Founder && Frontend Developer
  * Junwen Xia, summerhar666@gmail.com, , Co-Founder && Operations Manager

* How did you learn about our microgrant program?

    From Space Warp.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

    Not yet

  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @mingming-tang, this microgrant has been approved! We will send an email to confirm next steps.

**Comment by SpexJW** [comment]
> Hi @mingming-tang, this microgrant has been approved! We will send an email to confirm next steps.

Thank you Erin! We've already got it! really appreciate!!

**Comment by ErinOCon** [comment]
Hi @mingming-tang, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results: 

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin

Happy building!

**Comment by SpexJW** [comment]
> Hi @mingming-tang, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results:
> 
> * A fully working user-facing demo with nice UX that anyone case easily use.
> * Deployment to FVM mainnet - now that it has officially launched!
> * Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin
> 
> Happy building!

Hi Erin! Hope u r doing well! thank you for reaching out! we are currently updating website and demo, soon next week may have a nice UI&UX demo that could present and testing will be initiated following to try our best launch to mainnet ASAP! will definitely let u know here once the above complete! 

Thank you again and have a great one:)

**Comment by ErinOCon** [comment]
HI @mingming-tang and @SpexJW! Can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see https://github.com/filecoin-project/community/discussions/585#resources, or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

Please be in touch with any questions!

**Comment by ErinOCon** [comment]
Thank you for the update, @mingming-tang! Our team will be in touch with any questions @eshon

**Comment by SpexJW** [comment]
> Thank you for the update, @mingming-tang! Our team will be in touch with any questions @eshon

NP! Anytime! thank you again @ErinOCon :)

**Comment by SpexJW** [comment]
> Thank you for the update, @mingming-tang! Our team will be in touch with any questions @eshon

hey @ErinOCon! hope everything is going well! we want to share the exciting news that our project is already launched on the mainnet! here is our mainnet contract address:0xc284ff2a0bed6A72143423482739C9345c254924. please let me know if there is anything that needs to be provided in terms of determining the completeness of the micro-grant project! thank you so much:)

**Comment by eshon** [comment]
@SpexJW It looks like the contract at 0xc284ff2a0bed6A72143423482739C9345c254924 is now the beneficiary of the miners I just bought. What does this mean for my Filecoin Mainnet account at 0xc0C3Cab90DF2dF80e4bC7f0974E05571E50B130c? How is this account now related to SP [f02244810](https://filfox.info/en/address/f02244810)?

I wish I had something in my wallet representing my beneficiary status or ownership, like an NFT. Or is my account now basically an entry in the SPex registry?

**Comment by SpexJW** [comment]
> Hi @SpexJW! Thanks for your demo!
> 
> I tried to purchase 2 miners via these transactions on Mainnet and believe the transactions were successful:
> 
> * https://filfox.info/en/message/bafy2bzaceb6ce5bebi4gn3rc3p4kktv3gt4b2zjmey6g67hb6sitsnfhbwco2
> * https://filfox.info/en/message/bafy2bzacebpnmvgl6ow3e6o5cea4wt4u2sfxvyz4wbzm32zs7kcpt7z4p66oi
> 
> However I don't see any change in the Owner or Beneficiary of the related SPs. What is supposed to happen?
> 
> 2 comments:
> 
> 1. When I click "Buy" a MetaMask transaction initiates but it would be helpful to have a popup before that explaining what is going to happen.
> 2. I have bought 2 SPs but don't know what has happened. Am I now supposed to be Owner or Beneficiary of these 2 SPs? Can you please explain in the UI in a final confirmation window or popup of what has happened after the User has bought something?

hey @eshon !! thank you for the precious suggestions!! Indeed we need more notifications to explain each step, this is actually under development. we keep refining the UI/UX to make a better user experience for SPs. 

yes, you do have ownership of the miner account after you purchased it. and you could check the miner you just purchased on the Profile page which listed all the miner you possess in the contract. The change of ownership will explicitly show only when you transfer out the miner from the contract. The mapping of _minersDelegators in the contract maps the relationship between miners and delegators, you could check that. the relationship also reflects in the website Profile page. In short, the relationship between the new owner and the purchased miner will reflect only on the contract, only if you complete the step of the transfer out the miner from the contract to you, then this ownership will officially transfer to your address and the ownership address will present to yours on the chain, but before transfer out the miner, the ownership of the miner is still yours, just won't show the chain but will present/reflect in the contract. 

the reason why we design this way:
1. after buyers purchased the miners, they can relist the miner to the market again, as long as they didn't transfer out the miner from the contract. 
2. also transferring the ownership to the new owner require multiple steps, in order to prevent the situation that the miner needs to conduct multiple steps to finish purchasing(buy+ownership transfer) which will be time-consuming to conduct the one purchasing behavior, therefore we choose to break down the process of purchasing into two part(1. buy 2. transfer ownership whenever the buyer wants) and also this would help the first reason. 

hope I explained the questions properly, otherwise plz let me know I would love to try my best to explain it in another way.

thank you so much:)

**Comment by eshon** [comment]
That makes sense, thanks for the explanation!

**Comment by SpexJW** [comment]
> That makes sense, thanks for the explanation!


@eshon np at all! our pleasure! plz free feel let us know if there are any questions regarding determining if the FVM microgrant project is complete:)
