### ISSUE TITLE
Next Step Microgrant: KYContract - MyDonate

### ISSUE THREAD

**Issue by IssaKalonji** [filecoin-project/devgrants#1716]

**Comment by IKalonji** [comment]
Hi @ErinOCon this account @IssaKalonji  that created this grant application is an impersonator. Please assist in having this edited to reflect my correct details. He/She just copied my winning project from the FVM Dataverse Hack and submitted the application with my project.

I was in the process of completing a micro grant application for the above mentioned project but @IssaKalonji is an imposter account which just created today in my likeness to try and divert communication.

As you may be aware my Github is: https://github.com/IKalonji and email addr: ikalonji@student.wethinkcode.co.za and should be noted in Protocol Labs database since I'm a multiple hackathon winner and former grant recepient.

All links on this request belong to my project on Github and Devpost but the imposter used their own email address "moonlightwhisper7@gmail.com" and a newly created Github profile to redirect communication to themselves.

I'll send you a direct email in case this one is missed.
