### ISSUE TITLE
Microgrant Final Report: CID gravity Basic deal rate protection for retrieval market

### ISSUE THREAD

**Issue by ErinOCon** [filecoin-project/devgrants#603]
To meet the final report requirements for your microgrant, please answer each of the below questions. If code or demos are applicable to your work, please include a link with your report submission. 

1) Please briefly describe the work accomplished during the 3 month window of this microgrant. 
2) Did you meet the objectives outlined in your original microgrant application? If no, please briefly explain why.          
     **Note: We understand the objective(s) outlined may require adjusting as building progresses!         
3) What unexpected hurdles did you or your team encounter? How were these hurdles addressed (if any)?  
4) What next steps will you take for this project (if any)?
5) Please describe your experience building on IPFS and working with our team, including any challenges or shortcomings encountered.

**Comment by s0nik42** [comment]
Hi, 

The new feature developed with this grant, was related to implement retrieval deals in CID gravity allowing SPs to : 
- Protect their miners against DDOS
- Allow miners to manage and control retrieval deals. 

We follow the keep it simple approach, we provide a simple interface to miners to decide how many retrieval deals they accept per hour as follow : 

![image](https://user-images.githubusercontent.com/30711794/170359144-9fde695c-7862-4515-9bab-f74d390be16b.png)

We've got a large usage of the feature (initially requested by the SPX group). Since the feature launch more than 450,000 retrieval deals has been analysed across  our user base : 

![image](https://user-images.githubusercontent.com/30711794/170359724-20edd651-9669-4165-b1f2-9e07a63866ee.png)

> What unexpected hurdles did you or your team encounter? How were these hurdles addressed (if any)?

Not much, we get helpful support from the boost team. 

> What next steps will you take for this project (if any)?

Add more reporting and granular control on the retrieval market. 

> Please describe your experience building on IPFS and working with our team, including any challenges or shortcomings encountered.

We are developing around Filecoin for almost 2 years.  We find it more and more easy by multiplying contact we the PL teams, participating to PL summit, and next IPFS camp. 

Best,

Julien

**Comment by ErinOCon** [comment]
The project is complete and reporting is on file. This issue is resolved.
